spring:
  application:
    name: dream-shop
  datasource:
    url: jdbc:mysql://localhost:3306/dream_shop_db
    username: root
    password: 12344321
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true